USE [master]
GO
/****** Object:  Database [BBDDPROYECTO]    Script Date: 18/03/2024 10:02:39 ******/
CREATE DATABASE [BBDDPROYECTO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BBDDPROYECTO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BBDDPROYECTO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BBDDPROYECTO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BBDDPROYECTO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BBDDPROYECTO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BBDDPROYECTO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BBDDPROYECTO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET ARITHABORT OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BBDDPROYECTO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BBDDPROYECTO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BBDDPROYECTO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BBDDPROYECTO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BBDDPROYECTO] SET  MULTI_USER 
GO
ALTER DATABASE [BBDDPROYECTO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BBDDPROYECTO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BBDDPROYECTO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BBDDPROYECTO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BBDDPROYECTO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BBDDPROYECTO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BBDDPROYECTO] SET QUERY_STORE = OFF
GO
USE [BBDDPROYECTO]
GO
/****** Object:  Table [dbo].[CATEGORIAS_RESTAURANTES]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIAS_RESTAURANTES](
	[IDCATEGORIA] [int] NOT NULL,
	[NOMBRECATEGORIA] [nvarchar](100) NOT NULL,
	[ICONO] [nvarchar](200) NULL,
 CONSTRAINT [PK_CATEGORIAS_RESTAURANTES] PRIMARY KEY CLUSTERED 
(
	[IDCATEGORIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VALORACIONES_RESTAURANTE]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VALORACIONES_RESTAURANTE](
	[IDRESTAURANTE] [int] NOT NULL,
	[IDUSUARIO] [int] NOT NULL,
	[VALORACION] [int] NOT NULL,
 CONSTRAINT [PK_VALORACIONES_RESTAURANTE] PRIMARY KEY CLUSTERED 
(
	[IDRESTAURANTE] ASC,
	[IDUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RESTAURANTES]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESTAURANTES](
	[IDRESTAURANTE] [int] NOT NULL,
	[NOMBRE] [nvarchar](100) NOT NULL,
	[CORREO] [nvarchar](100) NOT NULL,
	[TELEFONO] [nvarchar](9) NULL,
	[DIRECCION] [nvarchar](200) NOT NULL,
	[IMAGEN] [nvarchar](200) NOT NULL,
	[IDCATEGORIA] [int] NOT NULL,
 CONSTRAINT [PK_RESTAURANTES] PRIMARY KEY CLUSTERED 
(
	[IDRESTAURANTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[V_RESTAURANTES]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[V_RESTAURANTES]
AS
	SELECT R.IDRESTAURANTE, R.NOMBRE, R.TELEFONO, R.CORREO,
	R.DIRECCION, R.IMAGEN, CR.NOMBRECATEGORIA,
	CAST(ISNULL(AVG(V.VALORACION), 0) AS DECIMAL(4,2)) AS VALORACION
	FROM RESTAURANTES R
	INNER JOIN CATEGORIAS_RESTAURANTES CR
	ON R.IDCATEGORIA = CR.IDCATEGORIA
	LEFT JOIN VALORACIONES_RESTAURANTE V
	ON R.IDRESTAURANTE = V.IDRESTAURANTE
	GROUP BY R.IDRESTAURANTE, R.NOMBRE, R.TELEFONO, R.CORREO,
	R.DIRECCION, R.IMAGEN, CR.NOMBRECATEGORIA
GO
/****** Object:  Table [dbo].[ESTADOS_PEDIDOS]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESTADOS_PEDIDOS](
	[IDESTADO] [int] NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_ESTADOS_PEDIDOS] PRIMARY KEY CLUSTERED 
(
	[IDESTADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTOS]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTOS](
	[IDPRODUCTO] [int] NOT NULL,
	[NOMBRE] [nvarchar](100) NOT NULL,
	[DESCRIPCION] [nvarchar](200) NULL,
	[PRECIO] [decimal](5, 2) NOT NULL,
	[IMAGEN] [nvarchar](200) NOT NULL,
	[IDRESTAURANTE] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTOS] PRIMARY KEY CLUSTERED 
(
	[IDPRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTOS_PEDIDO]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTOS_PEDIDO](
	[IDPEDIDO] [int] NOT NULL,
	[IDPRODUCTO] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTOS_PEDIDO] PRIMARY KEY CLUSTERED 
(
	[IDPEDIDO] ASC,
	[IDPRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PEDIDOS]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PEDIDOS](
	[IDPEDIDO] [int] NOT NULL,
	[IDUSUARIO] [int] NOT NULL,
	[IDRESTAURANTE] [int] NOT NULL,
	[ESTADO] [int] NOT NULL,
	[FECHAPEDIDO] [datetime] NOT NULL,
	[FECHAENTREGA] [datetime] NULL,
 CONSTRAINT [PK_PEDIDOS] PRIMARY KEY CLUSTERED 
(
	[IDPEDIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[V_PRODUCTOS_PEDIDO]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[V_PRODUCTOS_PEDIDO] AS
	SELECT P.IDPEDIDO, PR.IDPRODUCTO, R.NOMBRE AS RESTAURANTE,
	E.NOMBRE AS ESTADO, PR.NOMBRE AS PRODUCTO, PR.PRECIO, PP.CANTIDAD
	FROM PEDIDOS P
	INNER JOIN PRODUCTOS_PEDIDO PP
	ON P.IDPEDIDO = PP.IDPEDIDO
	INNER JOIN RESTAURANTES R
	ON P.IDRESTAURANTE = R.IDRESTAURANTE
	INNER JOIN PRODUCTOS PR
	ON PR.IDPRODUCTO = PP.IDPRODUCTO
	INNER JOIN ESTADOS_PEDIDOS E
	ON P.ESTADO = E.IDESTADO
GO
/****** Object:  Table [dbo].[CATEGORIAS_PRODUCTOS]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIAS_PRODUCTOS](
	[IDCATEGORIA] [int] NOT NULL,
	[IDRESTAURANTE] [int] NULL,
	[NOMBRECATEGORIA] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_CATEGORIAS_PRODUCTOS] PRIMARY KEY CLUSTERED 
(
	[IDCATEGORIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTO_CATEGORIAS]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTO_CATEGORIAS](
	[IDPRODUCTO] [int] NOT NULL,
	[IDCATEGORIA] [int] NOT NULL,
 CONSTRAINT [PK_PRODUCTO_CATEGORIAS] PRIMARY KEY CLUSTERED 
(
	[IDPRODUCTO] ASC,
	[IDCATEGORIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPOS_USUARIOS]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPOS_USUARIOS](
	[IDTIPO] [int] NOT NULL,
	[NOMBRETIPO] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_TIPOS_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[IDTIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[IDUSUARIO] [int] NOT NULL,
	[NOMBRE] [nvarchar](200) NOT NULL,
	[CORREO] [nvarchar](100) NOT NULL,
	[CONTRASENYA] [varbinary](max) NOT NULL,
	[SALT] [nvarchar](50) NULL,
	[TELEFONO] [nvarchar](9) NULL,
	[DIRECCION] [nvarchar](200) NOT NULL,
	[TIPOUSUARIO] [int] NOT NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[IDUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (1, 1, N'Entrantes')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (2, 1, N'Pizzas')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (3, 1, N'Postres')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (4, 2, N'Platos nuevos')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (5, 3, N'Cajas')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (6, 3, N'Galletas')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (7, 4, N'Burgers')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (8, 4, N'Ribs')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (9, 4, N'Entrantes')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (10, 5, N'Bowls')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (11, 5, N'Entrantes')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (12, 6, N'Menús')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (13, 6, N'Raciones')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (14, 7, N'Hamburguesas')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (15, 7, N'Entrantes')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (16, 8, N'Entrantes')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (17, 8, N'Especialidades')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (18, 9, N'Sándwiches')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (19, 9, N'Postres')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (20, 10, N'Entrantes')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (21, 10, N'Principales')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (22, 11, N'Pizzas')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (23, 11, N'Pastas')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (24, 11, N'Postres')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (25, 12, N'Market Plates')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (26, 12, N'Garden Bowls')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (27, 13, N'Top Ventas')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (28, 14, N'Ramen')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (29, 14, N'Clásicos')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (30, 15, N'Novedades')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (31, 16, N'Cinnabon')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (32, 16, N'Cinna Packs')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (33, 16, N'Bebidas')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (34, 17, N'Bowls')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (35, 17, N'Smoothies')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (36, 18, N'Baos')
GO
INSERT [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA], [IDRESTAURANTE], [NOMBRECATEGORIA]) VALUES (37, 18, N'Ramen')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (1, N'Americana', N'americana.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (2, N'Burger', N'burger.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (3, N'Árabe', N'arabe.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (4, N'China', N'china.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (5, N'Sandwich', N'sandwich.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (6, N'Dulces', N'dulces.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (7, N'India', N'india.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (8, N'Italiana', N'italiana.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (9, N'Japonesa', N'japonesa.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (10, N'Mexicana', N'mexicana.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (11, N'Pizza', N'pizza.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (12, N'Pollo', N'pollo.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (13, N'Sushi', N'sushi.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (14, N'Saludable', N'saludable.png')
GO
INSERT [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA], [NOMBRECATEGORIA], [ICONO]) VALUES (15, N'Smoothies', N'smoothie.png')
GO
INSERT [dbo].[ESTADOS_PEDIDOS] ([IDESTADO], [NOMBRE]) VALUES (1, N'SOLICITADO')
GO
INSERT [dbo].[ESTADOS_PEDIDOS] ([IDESTADO], [NOMBRE]) VALUES (2, N'PREPARANDO')
GO
INSERT [dbo].[ESTADOS_PEDIDOS] ([IDESTADO], [NOMBRE]) VALUES (3, N'EN PROCESO DE ENTREGA')
GO
INSERT [dbo].[ESTADOS_PEDIDOS] ([IDESTADO], [NOMBRE]) VALUES (4, N'ENTREGADO')
GO
INSERT [dbo].[PEDIDOS] ([IDPEDIDO], [IDUSUARIO], [IDRESTAURANTE], [ESTADO], [FECHAPEDIDO], [FECHAENTREGA]) VALUES (1, 2, 1, 3, CAST(N'2024-03-06T19:39:25.000' AS DateTime), NULL)
GO
INSERT [dbo].[PEDIDOS] ([IDPEDIDO], [IDUSUARIO], [IDRESTAURANTE], [ESTADO], [FECHAPEDIDO], [FECHAENTREGA]) VALUES (2, 2, 1, 2, CAST(N'2024-03-07T16:59:24.153' AS DateTime), NULL)
GO
INSERT [dbo].[PEDIDOS] ([IDPEDIDO], [IDUSUARIO], [IDRESTAURANTE], [ESTADO], [FECHAPEDIDO], [FECHAENTREGA]) VALUES (3, 2, 2, 1, CAST(N'2024-03-13T17:40:21.073' AS DateTime), NULL)
GO
INSERT [dbo].[PEDIDOS] ([IDPEDIDO], [IDUSUARIO], [IDRESTAURANTE], [ESTADO], [FECHAPEDIDO], [FECHAENTREGA]) VALUES (4, 3, 14, 1, CAST(N'2024-03-14T18:58:13.377' AS DateTime), NULL)
GO
INSERT [dbo].[PEDIDOS] ([IDPEDIDO], [IDUSUARIO], [IDRESTAURANTE], [ESTADO], [FECHAPEDIDO], [FECHAENTREGA]) VALUES (5, 22, 11, 1, CAST(N'2024-03-17T19:13:53.997' AS DateTime), NULL)
GO
INSERT [dbo].[PEDIDOS] ([IDPEDIDO], [IDUSUARIO], [IDRESTAURANTE], [ESTADO], [FECHAPEDIDO], [FECHAENTREGA]) VALUES (6, 22, 7, 1, CAST(N'2024-03-17T19:22:03.057' AS DateTime), NULL)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (1, 2)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (2, 2)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (3, 1)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (3, 2)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (4, 3)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (5, 2)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (6, 2)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (9, 4)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (11, 4)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (12, 5)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (13, 6)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (14, 6)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (15, 6)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (16, 6)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (17, 7)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (18, 7)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (19, 8)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (20, 9)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (21, 9)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (22, 10)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (23, 11)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (24, 10)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (25, 10)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (26, 12)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (27, 13)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (28, 13)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (29, 12)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (30, 14)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (31, 14)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (32, 14)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (33, 14)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (34, 15)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (35, 16)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (36, 17)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (37, 16)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (38, 17)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (39, 18)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (40, 18)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (41, 19)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (42, 18)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (43, 21)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (44, 21)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (45, 21)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (46, 20)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (47, 23)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (48, 22)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (49, 24)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (50, 23)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (51, 25)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (52, 25)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (53, 25)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (54, 25)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (55, 26)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (56, 27)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (57, 27)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (60, 28)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (61, 28)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (62, 29)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (63, 28)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (64, 28)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (66, 30)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (69, 31)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (70, 31)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (71, 32)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (72, 32)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (73, 33)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (74, 34)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (75, 34)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (76, 35)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (77, 35)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (78, 35)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (79, 36)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (80, 36)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (81, 37)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (82, 37)
GO
INSERT [dbo].[PRODUCTO_CATEGORIAS] ([IDPRODUCTO], [IDCATEGORIA]) VALUES (83, 36)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (1, N'Pizza Fugazzeta Rellena', N'Extra de mozarrella, cebolla dulce, ají molido y orégano', CAST(28.00 AS Decimal(5, 2)), N'img1.jpeg', 1)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (2, N'Pizza Posta', N'Mozzarella, portobello, yema de huevo, trufa y parmesano', CAST(23.00 AS Decimal(5, 2)), N'img2.jpeg', 1)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (3, N'Fainá o Farinata', N'Harina de garbanzos, pimienta blanca y cebollino', CAST(5.00 AS Decimal(5, 2)), N'img3.jpeg', 1)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (4, N'Tarta de Queso', N'Casera con mermelada', CAST(6.00 AS Decimal(5, 2)), N'img4.jpeg', 1)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (5, N'Pizza 4 Quesos', N'Mozzarella, parmesano, azul y stracciatella', CAST(23.00 AS Decimal(5, 2)), N'img5.jpeg', 1)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (6, N'Pizza Fumé', N'Pesto, mozzarella, scarmorza ahumada, cebolla, orégano', CAST(23.00 AS Decimal(5, 2)), N'img6.jpeg', 1)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (7, N'Ternera con Guindillas', N'Ternera, guindillas, perejil y soja', CAST(15.00 AS Decimal(5, 2)), N'img7.jpeg', 2)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (8, N'Arroz con Verdura y Carne Ahumada', N'Arroz, huevo, verdura y cerdo ahumado', CAST(10.50 AS Decimal(5, 2)), N'img8.jpeg', 2)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (9, N'Panceta de Mao', N'Panceta cocinada durante horas en azúcar, sal y especias', CAST(15.50 AS Decimal(5, 2)), N'img9.jpeg', 2)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (10, N'Panceta ahumada con ajetes tiernos', N'Panceta ahumada durante días con ajetes tiernos', CAST(15.00 AS Decimal(5, 2)), N'img10.jpeg', 2)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (11, N'Tallarines a las 36 especias', N'Uno de los platos más populares del desayuno en Hunan', CAST(12.00 AS Decimal(5, 2)), N'img11.jpeg', 2)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (12, N'Caja de Galletas (6 unidades)', N'Cajita con seis sabores distintos', CAST(18.50 AS Decimal(5, 2)), N'img12.jpeg', 3)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (13, N'Chocolate Chunk Cookie', N'Chocolate de leche y semidulce con un toque de sal', CAST(3.30 AS Decimal(5, 2)), N'img13.jpeg', 3)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (14, N'S''mores Cookie', N'Trozos de chocolate con nubes sobre una galleta graham', CAST(3.30 AS Decimal(5, 2)), N'img14.jpeg', 3)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (15, N'Red Velvet Cookie', N'Chocolate blanco, chocolate semidulce, cacao y nubes', CAST(3.30 AS Decimal(5, 2)), N'img15.jpeg', 3)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (16, N'Blueberry Cookie', N'Arándanos + limón + mantecado', CAST(3.30 AS Decimal(5, 2)), N'img16.jpeg', 3)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (17, N'Bacon Cheeseburger', N'Carne a la parrilla, con queso fundido, bacon crujiente y lechuga, tomate, cebolla y pepinillos', CAST(10.46 AS Decimal(5, 2)), N'img17.jpeg', 4)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (18, N'Ultimate Signature Burger', N'Dos carnes con nuestra salsa Fridays, queso fundido, bacon, cebolla caramelizada, mayonesa y lechuga.', CAST(11.72 AS Decimal(5, 2)), N'img18.jpeg', 4)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (19, N'Whiskey-Glaze Ribs', N'Costillas glaseadas con salsa Whiskey-Glaze y sazonadas con una mezcla de especias cajún, auténtico sabor americano.', CAST(10.88 AS Decimal(5, 2)), N'img19.jpeg', 4)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (20, N'Buffalo Wings', N'Alitas de pollo marinadas en salsa Buffalo picante, servidas con palitos de apio y salsa de queso azul.', CAST(9.95 AS Decimal(5, 2)), N'img20.jpeg', 4)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (21, N'Mozzarella Sticks', N'Dorados sticks de mozzarella con un perejil y queso rallado, acompañados de salsa marinara.', CAST(10.95 AS Decimal(5, 2)), N'img21.jpeg', 4)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (22, N'¡Está Padre!', N'Arroz, salsa blanca, cochinita, maíz, pico de gallo, piña, aguacate y cacahuetes', CAST(12.90 AS Decimal(5, 2)), N'img22.jpeg', 5)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (23, N'Crema de zanahoria', N'Crema de zanahoria con pimentón de la vera, aceite de oliva y cebollino', CAST(5.90 AS Decimal(5, 2)), N'img23.jpeg', 5)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (24, N'Pasión vegana', N'Arroz integral, tofu, salsa teriyaki, zanahoria, garbanzos, verduras, aguacate y cebolla', CAST(11.90 AS Decimal(5, 2)), N'img24.jpeg', 5)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (25, N'Mambo Italiano', N'Pasta integral, pollo asado con pesto, brócoli, tomate, huevo y queso feta.', CAST(13.90 AS Decimal(5, 2)), N'img25.jpeg', 5)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (26, N'Menú Dürüm', N'Pollo, cordero o mixto con patatas y bebida de 0.33 litros.', CAST(13.99 AS Decimal(5, 2)), N'img26.jpeg', 6)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (27, N'Patatas Fritas', N'Ración mediana', CAST(3.99 AS Decimal(5, 2)), N'img27.jpeg', 6)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (28, N'Dürüm Normal', N'Pan fino, carne o pollo, ensalada y salsa.', CAST(8.50 AS Decimal(5, 2)), N'img28.jpeg', 6)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (29, N'Menú Kebab', N'Pollo, cordero o mixto con patatas y bebida de 0.33 litros.', CAST(12.99 AS Decimal(5, 2)), N'img29.jpeg', 6)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (30, N'Hamburguesa Dirty Philly', N'Beyond meat, lechuga, tomate, pepinillos, cebolla caramelizada y salsa hoisin.', CAST(13.95 AS Decimal(5, 2)), N'img30.jpeg', 7)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (31, N'Hamburguesa Double Cheese Bacon', N'Burger de heura, doble queso vegano, bacon, lechuga, tomate, pepinillos y cebolla roja.', CAST(13.95 AS Decimal(5, 2)), N'img31.jpeg', 7)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (32, N'Hamburguesa Rock''n Chick''n', N'Pollo crujiente, lechuga, tomate, pepinillos, mix cebolla y crujiente, queso vegano, vegan mayo y salsa MAD.', CAST(12.95 AS Decimal(5, 2)), N'img32.jpeg', 7)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (33, N'Hamburguesa Mad Signature', N'Beyond meat, lechuga, tomate, pepinillos, mix cebolla roja y crujiente, queso vegano fundido y salsa MAD.', CAST(13.95 AS Decimal(5, 2)), N'img33.jpeg', 7)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (34, N'Homemade Buffalo Coli Wings', N'Alitas de coliflor con nuestro rebozado secreto a las 7 especias y salsa casera búffalo.', CAST(7.50 AS Decimal(5, 2)), N'img34.jpeg', 7)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (35, N' Menú Mayura', N'Entrante con cuatro salsas, Curry Hindú con Bebida, acompañado de Arroz Basmati o Pan Naan', CAST(14.90 AS Decimal(5, 2)), N'img35.jpeg', 8)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (36, N'Pollo Tikka Masala', N'Excepcional plato de pollo con una exquisita salsa de tomate y cebolla.', CAST(13.90 AS Decimal(5, 2)), N'img36.jpeg', 8)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (37, N'Arroz Basmati (Vegano)', N'Arroz tradicional y aromático hecho a fuego lento', CAST(4.80 AS Decimal(5, 2)), N'img37.jpeg', 8)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (38, N'Pollo Makhani', N'Una delicia cremosa de pollo tandoori con queso, tomate y mantequilla.', CAST(13.90 AS Decimal(5, 2)), N'img38.jpeg', 8)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (39, N'Smashed Sandwich', N'180 gr. de carne de vaca gallega. Con queso cheddar, emmental y nuestra salsa secreta.', CAST(13.75 AS Decimal(5, 2)), N'img39.jpeg', 9)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (40, N'Pastrami', N'Sándwich a la plancha con queso suizo, cebolla encurtida, mostaza picante y pastrami.', CAST(13.75 AS Decimal(5, 2)), N'img40.jpeg', 9)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (41, N'Chocolate Chip Cookie Gigante', N'La galleta casera más adictiva, crujiente y blandita al mismo tiempo.', CAST(2.95 AS Decimal(5, 2)), N'img41.jpeg', 9)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (42, N'Cubano', N'Cerdo asado, jamón, salami, queso suizo, pepinillos y mostaza picante.', CAST(11.95 AS Decimal(5, 2)), N'img42.jpeg', 9)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (43, N'Quesatacos (Dos Coyotes)', N'Tortillas de maíz rellena de queso monterrey, birria de ternera o pollo, cilantro y cebolla.', CAST(10.43 AS Decimal(5, 2)), N'img43.jpeg', 10)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (44, N'Burrito de birria', N'Birria de ternera, queso monterrey, arroz criollo, alubias negras, cilantro, cebolla y nuestra mayo chipotle.', CAST(11.50 AS Decimal(5, 2)), N'img44.jpeg', 10)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (45, N' Quesadilla', N'Tortilla de trigo rellena de queso monterrey, cebolla y cilantro con guacamole, crema agria, y pico de gallo.', CAST(9.90 AS Decimal(5, 2)), N'img45.jpeg', 10)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (46, N'Birria Beef Bowl', N'Birria de ternera cocida en sus jugos, arroz criollo, frijoles negros , pico de gallo fresco, guacamole y crema agria', CAST(12.95 AS Decimal(5, 2)), N'img46.jpeg', 10)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (47, N'TAGLIATELLE DE BOLOGNA', N'Ternera picada, salsa pomodoro, láminas de parmesano con romero.', CAST(14.50 AS Decimal(5, 2)), N'img47.jpeg', 11)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (48, N'REGINA MARGHERITA DI BUFALA', N'Tomate, mozzarella de búfala y albahaca fresca.', CAST(12.50 AS Decimal(5, 2)), N'img48.jpeg', 11)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (49, N'TIRAMISU', N'Nuestro postre favorito hecho diariamente en nuestro local.', CAST(6.50 AS Decimal(5, 2)), N'img49.jpeg', 11)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (50, N'GNOCCHI CON TOMATE CONFITADO', N'Tomate siciliano confitado, salsa pomodoro, albahaca y nubes de burrata.', CAST(13.90 AS Decimal(5, 2)), N'img50.jpeg', 11)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (51, N'Ben’s Sweet Potato Fries', N'Las chips de boniato de nuestro Chef Ben acompañadas de beet ketchup, alioli plant-based y cilantro.', CAST(5.90 AS Decimal(5, 2)), N'img51.jpeg', 12)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (52, N'Pollo Piri Piri', N' Pollo Piri Piri 8,90 € Contramuslo de pollo de corral, deshuesado y marinado en nuestra mezcla secreta de hierbas y especias Piri Piri, con picada de piña, tomate y cilantro.', CAST(8.90 AS Decimal(5, 2)), N'img52.jpeg', 12)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (53, N'Pollo con Hierbas', N'Pechuga de pollo de corral, marinada con hierbas mediterráneas, salsa de alcaparras y limón. Hecha al horno Josper.', CAST(8.90 AS Decimal(5, 2)), N'img53.jpeg', 12)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (54, N'Falafel con salsa Tahini', N'Mezcla de garbanzos, puerros, pimientos, comino y hierbas, acompañado de salsa tahini. Elaborado con orujo de aceite de oliva.', CAST(8.90 AS Decimal(5, 2)), N'img54.jpeg', 12)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (55, N'Latin Lover', N'Arroz integral, frijoles, kale, cilantro, lombarda, maíz, cebolla, aguacate, pepino, jalapeños encurtidos y pico de gallo. Salsa sour cream y jalapeño asado.', CAST(8.90 AS Decimal(5, 2)), N'img55.jpeg', 12)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (56, N'Pollo Gangnam Style', N'8x Pollo frito con salsa gochujang, dulce y muy poco picante', CAST(9.95 AS Decimal(5, 2)), N'img56.jpeg', 13)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (57, N'Dobboki', N'Entrante coreano hecho base de TTEOK (pastel de arroz) acompañado de OMUK (pastel de pescado)', CAST(6.95 AS Decimal(5, 2)), N'img57.jpeg', 13)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (58, N'Chuck Chuck Double Joy Plus', N'Combination clásica. 6x Gangnam Style + 6x Honey Mustard', CAST(16.95 AS Decimal(5, 2)), N'img58.jpeg', 13)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (59, N'Double Joy Set', N'6x Pollo Frito Gangnam + 6x Pollo Frito Honey, 1x patatas fritas, 1x ensalada de maíz, 2x bebidas', CAST(24.95 AS Decimal(5, 2)), N'img59.jpeg', 13)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (60, N'Ramen Lomo Alto y Trufa', N'Noodles caseros con lomo alto, huevo a baja temperatura, verduras en caldo de ternera con un toque de trufa.', CAST(14.95 AS Decimal(5, 2)), N'img60.jpeg', 14)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (61, N'Ramen Spicy', N'Noodles caseros con lomo picado de ternera, huevo a baja temperatura y verduras en caldo de cerdo con un toque picante. Terminado con filamentos de guindilla.', CAST(14.95 AS Decimal(5, 2)), N'img61.jpeg', 14)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (62, N'Gyozas de Pollo', N'Empanadillas japonesas al estilo Ninja rellenas de pollo y especias con nuestra salsa mayonesa de mantequilla y chile infusionada con sésamo.', CAST(7.00 AS Decimal(5, 2)), N'img62.jpeg', 14)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (63, N'Ramen Curry con Pollo', N'Noodles caseros con contramuslo de pollo, huevo a baja temperatura y verduras en caldo de pollo con salsa de curry japonés', CAST(13.90 AS Decimal(5, 2)), N'img63.jpeg', 14)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (64, N'Tonkatsu Black Ramen', N'Ramen con char siu (aguja de cerdo), aceite de ajo negro y caldo de tonkatsu (hueso de cerdo).', CAST(14.95 AS Decimal(5, 2)), N'img64.jpeg', 14)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (65, N'Salmon Crush', N'8 rolls. Salmón, aguacate, crema de queso, envuelto en salmón, salsa de almíbar de naranja, sriracha y cheese furikake.', CAST(9.31 AS Decimal(5, 2)), N'img65.jpeg', 15)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (66, N'Tuna Tartufata', N'Extra de aguacate, mayonesa japonesa y envuelto de tartar de atún flambeado, aceite de trufa negra y cebollino.', CAST(10.45 AS Decimal(5, 2)), N'img66.jpeg', 15)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (67, N'Kioto', N'8 rolls. Aguacate, crema de queso, cebolla caramelizada, envuelto de salmón tataki, salsa teriyaki y flor de sal.', CAST(9.95 AS Decimal(5, 2)), N'img67.jpeg', 15)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (68, N'Duck Bao', N'2 bollitos asiáticos de pan al vapor con pato asado, mayonesa, cebolla tierna china y nuestra salsa Koreana.', CAST(9.95 AS Decimal(5, 2)), N'img68.jpeg', 15)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (69, N'Cinnabon Classic', N'Es el rey de nuestros sabores, con su inconfundible aroma a canela makara.', CAST(3.90 AS Decimal(5, 2)), N'img69.jpeg', 16)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (70, N'Caramel Pecanbon', N'Es un viaje de sabores, lleva canela, glaseado y nueces pecanas.', CAST(4.50 AS Decimal(5, 2)), N'img70.jpeg', 16)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (71, N'Minibon Classic', N'Minibon, una divertida delicia.', CAST(2.80 AS Decimal(5, 2)), N'img71.jpeg', 16)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (72, N'Cinna Pack Clásico', N'Para darle un toque dulce a las celebraciones y aniversarios.', CAST(12.00 AS Decimal(5, 2)), N'img72.jpeg', 16)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (73, N'Roll on the Go & Chillatta', N'Para endulzar el día.', CAST(5.65 AS Decimal(5, 2)), N'img73.jpeg', 16)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (74, N'Açai Pai Bowl', N'Toppings: granola, fresa, plátano y arándanos.  Mezcla; skyr, fresa, plátano, arándanos y açai.  Base: skyr.', CAST(8.90 AS Decimal(5, 2)), N'img74.jpeg', 17)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (75, N'Moon Nights Bowl', N'Toppings; granola, fresa, plátano, mantequilla de cacahuete, piña y chocolate negro.  Mezcla; leche almendras, mango,plátano, piña, datiles, almendras y mantequilla de cacahuete. Base; skyr.', CAST(8.90 AS Decimal(5, 2)), N'img75.jpeg', 17)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (76, N'El Madrileño', N'Skyr, arándanos, fresa, frambuesa, pera, plátano y manzana roja.', CAST(7.90 AS Decimal(5, 2)), N'img76.jpeg', 17)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (77, N'Gym Bro', N'Skyr, fresa, mantequilla de cacahuete, datiles, manzana y proteina whey.', CAST(7.90 AS Decimal(5, 2)), N'img77.jpeg', 17)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (78, N'Moon Nights', N'Skyr, dátiles, almendras, mango, plátano, mantequilla de cacahuete, naranja, piña y manzana roja.', CAST(7.90 AS Decimal(5, 2)), N'img78.jpeg', 17)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (79, N'Kakuni Bao de Panceta', N'Bao al vapor de tierna panceta de cerdo braseada en jugo especiado, emulsión de hierbas, mostaza japonesa, pepinillo y lechuga.', CAST(5.90 AS Decimal(5, 2)), N'img79.jpeg', 18)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (80, N'Ebi Bao de langostino', N'Bao al vapor langostino tempurizado, salsa cremosa picante y lechuga con vinagreta de yuzu.', CAST(5.50 AS Decimal(5, 2)), N'img80.jpeg', 18)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (81, N'Shoyu Tôkyô Ramen', N'Caldo de pollo y dashi aderezado con shoyu macerado, noodles, 1/2 huevo marinado ajitama, 2 lonchas de chashu de cerdo fraseado, nori y vegetales.', CAST(15.90 AS Decimal(5, 2)), N'img81.jpeg', 18)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (82, N'Yuzu Shio Ramen', N'Caldo de pollo y dashi aderezado con sal y yuzu. Con noodles, 1/2 huevo marinado ajitama, 2 lonchas de chashu de cerdo fraseado, nori y vegetales.', CAST(15.50 AS Decimal(5, 2)), N'img82.jpeg', 18)
GO
INSERT [dbo].[PRODUCTOS] ([IDPRODUCTO], [NOMBRE], [DESCRIPCION], [PRECIO], [IMAGEN], [IDRESTAURANTE]) VALUES (83, N'Karaage Bao de pollo', N'Bao al vapor de pollo marinado y tempurizado (karaage), salsa tártara japonesa y rúcula.', CAST(5.50 AS Decimal(5, 2)), N'img83.jpeg', 18)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (1, 1, 2)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (1, 2, 1)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (2, 4, 4)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (2, 5, 1)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (3, 11, 2)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (4, 60, 1)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (4, 61, 2)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (5, 47, 2)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (5, 50, 1)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (6, 30, 1)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (6, 33, 2)
GO
INSERT [dbo].[PRODUCTOS_PEDIDO] ([IDPEDIDO], [IDPRODUCTO], [CANTIDAD]) VALUES (6, 34, 4)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (1, N'Pizza Posta', N'pizzaposta@gmail.com', N'915700738', N'Calle del Amparo, 81, 28012 Madrid, España', N'img1.jpeg', 11)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (2, N'Chila', N'chilarestaurante@gmail.com', N'915302673', N'Calle De Silva 4, Madrid, Madrid 28013', N'img2.jpeg', 4)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (3, N'Bells Cookie Co', N'bellscookie@gmail.com', N'699413217', N'Calle del Conde de Peñalver, 66, 28006 Madrid, España', N'img3.jpeg', 6)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (4, N'Fridays', N'fridaysburgers@gmail.com', N'681390215', N'Paseo de La Habana, 17, 28036 Madrid, España', N'img4.jpeg', 1)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (5, N'SANABOWLS', N'sanabowls@gmail.com', N'921732155', N'Calle de Vallehermoso, 42, 28015 Madrid, España', N'img5.jpeg', 14)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (6, N'Nemrut Legazpi', N'kebabnemrut@gmail.com', N'687389301', N'Paseo del Molino, 1, 28045 Madrid, España', N'img6.jpeg', 3)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (7, N'Mad Mad Vegan', N'madmadvegan@gmail.com', N'673291355', N'Calle de Lavapiés, 16, 28012 Madrid, España', N'img7.jpeg', 2)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (8, N'Mayura', N'mayura@gmail.com', N'977532104', N'Paseo de los Melancólicos, 7, 28005 Madrid, España', N'img8.jpeg', 7)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (9, N'Saboriz Sandwich', N'saboriz@gmail.com', N'934760241', N'Calle de Modesto Lafuente, 64, 28003 Madrid, España', N'img9.jpeg', 5)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (10, N'Birrieria Dos Coyotes', N'doscoyotes@gmail.com', N'912834710', N'Calle de San Bernardo, 86, 28015 Madrid, España', N'img10.jpeg', 10)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (11, N'Oven', N'overpasta@gmail.com', N'911552107', N'Calle de Fuencarral, 74, 28004 Madrid, España', N'img11.jpeg', 8)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (12, N'Honest Greens', N'honestgreens@gmail.com', N'677482531', N'Calle de Fuencarral, 95, 28004 Madrid, España', N'img12.jpeg', 14)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (13, N'CHUCKCHUCK CHICKEN', N'chuckchuck@gmail.com', N'989302135', N'Calle del Mesón de Paredes, 45, 28012 Madrid, España', N'img13.jpeg', 12)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (14, N'Ninja Taberna', N'ninjataberna@gmail.com', N'943437890', N'Calle de la Princesa, 13, 28008 Madrid, EMEA, España', N'img14.jpeg', 9)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (15, N'TEIKIT', N'teikit@gmail.com', N'987613000', N'Calle Imperial, 18, 28012 Madrid, España', N'img15.jpeg', 13)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (16, N'Cinnabon', N'cinnabon@gmail.com', N'671224088', N'Cc Principe Pio, Paseo de la Florida, 2, 28008 Madrid, España', N'img16.jpeg', 6)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (17, N'Skyrland', N'skyrland@gmail.com', N'922653313', N'Calle de Sandoval, 6, 28010 Madrid, España', N'img17.jpeg', 15)
GO
INSERT [dbo].[RESTAURANTES] ([IDRESTAURANTE], [NOMBRE], [CORREO], [TELEFONO], [DIRECCION], [IMAGEN], [IDCATEGORIA]) VALUES (18, N'Hattori Hanzo', N'hattorihanzo@gmail.com', N'673219073', N'Calle de Mesonero Romanos, 17, 28004 Madrid, España', N'img18.jpeg', 9)
GO
INSERT [dbo].[TIPOS_USUARIOS] ([IDTIPO], [NOMBRETIPO]) VALUES (1, N'USUARIO')
GO
INSERT [dbo].[TIPOS_USUARIOS] ([IDTIPO], [NOMBRETIPO]) VALUES (2, N'ADMIN')
GO
INSERT [dbo].[TIPOS_USUARIOS] ([IDTIPO], [NOMBRETIPO]) VALUES (3, N'EMPRESA')
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (1, N'admin', N'admin@gmail.com', 0x4E08BA2A17F5E94E920D1EEFB161E725A9BC02C8AA0F8BDE6356686DC3A66E391D1B3EE98679426B364D5E7238130B7E8A4C022161A2A436A2BBB6BD08A3E53B, N'.èMQJlDª©ÞbVu7ß@êçN©ýPÕWN]©n½|ÎñT¢x³±zùWñ¶', N'617812153', N'Calle Villaverde 14, Getafe, Madrid', 2)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (2, N'Alejandro López Labajo', N'alopezlabajo.02@gmail.com', 0xA658D3FBAE1FFCDA5179DDD0A2F16A41348871010C5C87F80DAE2C03D3A3407CF818E4EF47F0C5D556F5966F4ACBB57C1CDE1154FBABCA49FE10A7950F6275CD, N'ª<CEéÎ&Ñ¹x]Dï&Y£,ìÀ=Òâé,@»À£aUÌýns¶''RG', N'617812153', N'Calle del Vizconde de Arlessón, 33, 28018 Madrid, España', 1)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (3, N'Prueba Usuario', N'pruebausuario@gmail.com', 0x4E392A7AB2BEE7379439D12BE0D96495F18A526576A788F5137EB563B3DB6B93F74A83CFBD850401E11E06AF76A9ED7CD597F46CC2DF000236B64A1642097F9A, N'ûÄº-)Ò*èª*¸Ð%¶ûMÖñÈýiÑ",r)S6°öÅþ¤zñà#/S\', N'643438790', N'Calle de la Princesa, 56, 28008 Madrid, España', 1)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (4, N'Pizza Posta', N'pizzaposta@gmail.com', 0x376A43060B092E9B2D0B435C08C06B01B88C7307A2B397E8671F619202BF334F5A49B46EF116D71A38F93FBB59FDBA4B49713F3191A42CF97937F2C388718426, N'ËÑ£)Úê9XJ}]T¤pXæÅÞz0³°¿öÚüDÕ¹@y/aåÏ', N'915700738', N'Calle del Amparo, 81, 28012 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (5, N'Chila', N'chilarestaurante@gmail.com', 0xCF1F7932D021FF10EB3001FB7EE61650BC5987F7788E52EE6D20DC92EBB56FCBA17D41CA0A0311153E8771711422D409E863A52A074B943CE1AD9BB0A782A6DC, N'²ºßøQ¸>¹rZ<í\®Õ¨"¶TÉEV bþ17*ïcz \+P¹U#½Ï', N'915302673', N'Calle De Silva 4, Madrid, Madrid 28013', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (6, N'Bells Cookie Co', N'bellscookie@gmail.com', 0xEE5758A5A974C13D8EF841235AD4D09B20D10F7B1B0BB0B6C7378F812785F1CBC8FBC85D34B5EEF66FC7F4F42760C441C184625170D08742361AE3A31047DFA1, N'oæBö¦%Ë¼ÖÀ~¹þ¿=Ç1IËø­#á¶³ÛòÀë«ë1Ô
ðè:', N'699413218', N'Calle del Conde de Peñalver, 66, 28006 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (7, N'Fridays', N'fridaysburgers@gmail.com', 0x486198B9BFF3BD39F09CD282DEE0877D46FD0F0856FA3F560D8E3D18859CF39603714C0935BA598D49651B60887DBD38999A1E20100D5EA5506825B7486F422A, N'[¶ÖßË£gF	øxfU7#iì%Cê	ÖêÍµnÍÌ}Ë¡} Æ', N'681390215', N'Paseo de La Habana, 17, 28036 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (8, N'SANABOWLS', N'sanabowls@gmail.com', 0xDB843D80E771A2B1B87F92FBAA7B8A2CEEC681151B734654C02389C623FF980D7ABCE086FB6976DE576B5D3A817801BB2EDD2BEFCA116EBE9811D2FD08ED0B14, N':ÅÒ5^¸ÀXðÛÚÆ¥_?Q°»é6ÂÉC,G»y''3ëíÂxo,8On', N'921732155', N'Calle de Vallehermoso, 42, 28015 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (9, N'Kebab Nemrut Legazpi', N'kebabnemrut@gmail.com', 0xFFFCCEFDF1B93CA023EE9401D9AAD7FCE5E3F3189C5161402CD0AE6D9E947A3E47294A60311B6CDDDA042A845A7EC838F28C73C90FB300A4A899A87C427DB11B, N' <Ïé"^!Æ¡c&»j;«¿0\Kþ1è³¨åJÊã#?4p*ö½­z', N'687389301', N'Paseo del Molino, 1, 28045 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (10, N'Mad Mad Vegan', N'madmadvegan@gmail.com', 0x51C0440DDC71322728A009AACB7266DAC8142D98C963AEB4ECACF67968963EAEBBC6E3D3864AF749C8A7668747F4FA36E6C8A3915E22DE782130D14F64BF18A4, N'è:?eÀ¶¿ÞïOéªë	öFãü$õ©Ó{||îíÅü<}MÏ¥ÁÄÐ', N'673291355', N'Calle de Lavapiés, 16, 28012 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (11, N'Mayura', N'mayura@gmail.com', 0x0F812082C404538CD898F5911163F35F990F91C12AF02E7965DE9A4D2363D3E8D9975CE86B63E75FD8F49FE28D53D219B47838673AAC212BFC934ED3ACC03B74, N'HßÚ`^ÎhEÏÆã}ºtºí=ýË{ÉÑðáõ''!þì¤«ÎwHðâ¼ioÄg', N'977532104', N'Paseo de los Melancólicos, 7, 28005 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (12, N'Saboriz Sandwich', N'saboriz@gmail.com', 0x374726B4DE479E4A6137322D5B83F0847CA90BFB29F893534254B08BC9FD0A87148FC9EBF0ACAE9EE4A843221166183D47F9AAAD7D576BF74CCAA0EF874E7F83, N'ÚÔ1Ë­²Pí_õaÕCX¡Ì0©µêÒ¶ÌìynpTí!Dî¯ª"Û×¢º', N'934760241', N'Calle de Modesto Lafuente, 64, 28003 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (13, N'Birrieria Dos Coyotes', N'doscoyotes@gmail.com', 0xEEDF27D4314ED5F74E70E15B6CB9066537A2156CD1BE65E44D663ED6BF21687802653410EA4F16F7271A78E22F3801A1A8A7EB759AF0E44C59303051EB59D075, N'íBpgZrÀÖ$1bHßÙ¡ãJÜÐó4.7\KJ°×ÓjX%¾µ´P', N'912834710', N'Calle de San Bernardo, 86, 28015 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (14, N'Oven', N'overpasta@gmail.com', 0x96E1A0B1286B940FE885EE431FCB43FDFA0DB918B31AB9F46E61316D38C043E26B14C3F29374E46472637DAF106E6265C36EC3B7E926AE5E3A1472834F149271, N'×KÎ;CqOÆãHäJ
¹ F ¼ÃÔ_{ÑæýM++ts{$/& IþÁnüÌ', N'911552107', N'Calle de Fuencarral, 74, 28004 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (15, N'Honest Greens', N'honestgreens@gmail.com', 0xB61589566DB8F39BE557E2A6156C05FC7F516640FC61305554852A2D990C8CE67141970652AFB724B51C266F99622B6F4BD4FC86FE2185E6B1EBC2DF83D31724, N'E¨(2i^þX¯Z ¦U¦kÂdïþÑ4¬BC¶ü''¹kX]^', N'677482531', N'Calle de Fuencarral, 95, 28004 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (16, N'CHUCK CHUCK CHICKEN', N'chuckchuck@gmail.com', 0xC3DD2F12C61D5E07D3FAFE4148CFD72B32CF1B30D20F048665337B1766404804C0372074689F8C5F7BA70A6630A5174B30E910B292B74FB3EA72E5F8F3779970, N'¡BtF·ìÁÉÂ²Û<©NèÚUæSùz¼Xìó)®TÉTÄù4ßêiåTô', N'989302135', N'Calle del Mesón de Paredes, 45, 28012 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (17, N'Ninja Taberna', N'ninjataberna@gmail.com', 0x094A0311E29120C207FD2E7C32A0CDC4C5CBA278656D0099C7A624785858B60F46B97ADD0E559AB6D05877F60AFF4F5FE50F948EEBE1341F7B0CC62E436BDF5B, N'¤~hÙ@éÇÎ Kr#£¸¡)=DØ3iÐèªñ¸&ò2,4qÚ¹A¤', N'943437890', N'Calle de la Princesa, 13, 28008 Madrid, EMEA, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (18, N'TEIKIT', N'teikit@gmail.com', 0x34A009D95877A59D60E06CCB29248A3757E7D649977FF0E67E5C78832749DB3CCF7D6EC56FD5477DB4B223C83BEBA0089167E7079226B974A8E68F540BE62058, N''' YZp\zj+#0%×Íq·)UwÛ{wÑ:É;ÝYS»SRý¦[Ý9ù	', N'987613000', N'Calle Imperial, 18, 28012 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (19, N'Cinnabon', N'cinnabon@gmail.com', 0xE57429867F46169C7D294A3B4371302888B466D30E5C28414663B05BAF73A1438723F653711B426C3BE5CDB4E3998E78AE57CAF7ED0AF63AF586F3DE8E79538B, N'Ds»Eðöâè£þÍ¡¶¿O­eölarÙÏ`%¾qIvwä»å(x®Ûíg>·ß32', N'671224088', N'Cc Principe Pio, Paseo de la Florida, 2, 28008 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (20, N'Skyrland', N'skyrland@gmail.com', 0xEE7C6738E8D7BEE8A2A16918EA9FCE4FB94E1A8852F3A297FC993CD8C1A346536269C4345CB58572E40F4F5019AA01E6CF719858C0FDBC82214B01D5A1A7E140, N'3)³ì6¼Ã**wæ¶­8%ÞC
uü¹¦IWOèW`m@ÒµP', N'922653313', N'Calle de Sandoval, 6, 28010 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (21, N'Hattori Hanzo', N'hattorihanzo@gmail.com', 0xD9283ACDF81BE1CF7AF4999AF9CEE374D7FB75F99D5B0F3AA0352130C376C36E38FF2FB68928142F84E6FA14E1AD6389C1DECAA62996710C7F36984C10529BB2, N'FX¥ËCYÃäØmó3~ûáÇì]Îâ"-8ÑD8¿5º|×o¿TGø¢ñôÔ¦¨Û', N'673219073', N'Calle de Mesonero Romanos, 17, 28004 Madrid, España', 3)
GO
INSERT [dbo].[USUARIOS] ([IDUSUARIO], [NOMBRE], [CORREO], [CONTRASENYA], [SALT], [TELEFONO], [DIRECCION], [TIPOUSUARIO]) VALUES (22, N'Tabe Test', N'tabetesttajamar@outlook.com', 0xF7C634A48B57B881F607A7C51A97AA6C6B8038450B962672BB940398A13B5784A0E9B672EAB5323E261627369028C44E799CE7D4B0771E23E15E1A587606E805, N'''ªÈ¾>rt¾ï²àgðòI½äñs»YBUÓÄUn°n1G¡×®EÔM#', N'643436790', N'Paseo de La Habana, 17, 28036 Madrid, España', 1)
GO
INSERT [dbo].[VALORACIONES_RESTAURANTE] ([IDRESTAURANTE], [IDUSUARIO], [VALORACION]) VALUES (1, 1, 4)
GO
INSERT [dbo].[VALORACIONES_RESTAURANTE] ([IDRESTAURANTE], [IDUSUARIO], [VALORACION]) VALUES (1, 2, 5)
GO
INSERT [dbo].[VALORACIONES_RESTAURANTE] ([IDRESTAURANTE], [IDUSUARIO], [VALORACION]) VALUES (2, 1, 3)
GO
INSERT [dbo].[VALORACIONES_RESTAURANTE] ([IDRESTAURANTE], [IDUSUARIO], [VALORACION]) VALUES (2, 2, 4)
GO
INSERT [dbo].[VALORACIONES_RESTAURANTE] ([IDRESTAURANTE], [IDUSUARIO], [VALORACION]) VALUES (6, 2, 4)
GO
INSERT [dbo].[VALORACIONES_RESTAURANTE] ([IDRESTAURANTE], [IDUSUARIO], [VALORACION]) VALUES (11, 3, 5)
GO
INSERT [dbo].[VALORACIONES_RESTAURANTE] ([IDRESTAURANTE], [IDUSUARIO], [VALORACION]) VALUES (12, 2, 3)
GO
/****** Object:  Index [UNIQUE_CORREO_RESTAURANTES]    Script Date: 18/03/2024 10:02:39 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UNIQUE_CORREO_RESTAURANTES] ON [dbo].[RESTAURANTES]
(
	[IDRESTAURANTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UNIQUE_CORREO_USUARIOS]    Script Date: 18/03/2024 10:02:39 ******/
ALTER TABLE [dbo].[USUARIOS] ADD  CONSTRAINT [UNIQUE_CORREO_USUARIOS] UNIQUE NONCLUSTERED 
(
	[CORREO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_PEDIDOS_ESTADOS_PEDIDOS] FOREIGN KEY([ESTADO])
REFERENCES [dbo].[ESTADOS_PEDIDOS] ([IDESTADO])
GO
ALTER TABLE [dbo].[PEDIDOS] CHECK CONSTRAINT [FK_PEDIDOS_ESTADOS_PEDIDOS]
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_PEDIDOS_RESTAURANTES] FOREIGN KEY([IDRESTAURANTE])
REFERENCES [dbo].[RESTAURANTES] ([IDRESTAURANTE])
GO
ALTER TABLE [dbo].[PEDIDOS] CHECK CONSTRAINT [FK_PEDIDOS_RESTAURANTES]
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_PEDIDOS_USUARIOS] FOREIGN KEY([IDUSUARIO])
REFERENCES [dbo].[USUARIOS] ([IDUSUARIO])
GO
ALTER TABLE [dbo].[PEDIDOS] CHECK CONSTRAINT [FK_PEDIDOS_USUARIOS]
GO
ALTER TABLE [dbo].[PRODUCTO_CATEGORIAS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTO_CATEGORIAS_CATEGORIAS_PRODUCTOS] FOREIGN KEY([IDCATEGORIA])
REFERENCES [dbo].[CATEGORIAS_PRODUCTOS] ([IDCATEGORIA])
GO
ALTER TABLE [dbo].[PRODUCTO_CATEGORIAS] CHECK CONSTRAINT [FK_PRODUCTO_CATEGORIAS_CATEGORIAS_PRODUCTOS]
GO
ALTER TABLE [dbo].[PRODUCTO_CATEGORIAS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTO_CATEGORIAS_PRODUCTOS] FOREIGN KEY([IDPRODUCTO])
REFERENCES [dbo].[PRODUCTOS] ([IDPRODUCTO])
GO
ALTER TABLE [dbo].[PRODUCTO_CATEGORIAS] CHECK CONSTRAINT [FK_PRODUCTO_CATEGORIAS_PRODUCTOS]
GO
ALTER TABLE [dbo].[PRODUCTOS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTOS_RESTAURANTES] FOREIGN KEY([IDRESTAURANTE])
REFERENCES [dbo].[RESTAURANTES] ([IDRESTAURANTE])
GO
ALTER TABLE [dbo].[PRODUCTOS] CHECK CONSTRAINT [FK_PRODUCTOS_RESTAURANTES]
GO
ALTER TABLE [dbo].[PRODUCTOS_PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTOS_PEDIDO_PEDIDOS] FOREIGN KEY([IDPEDIDO])
REFERENCES [dbo].[PEDIDOS] ([IDPEDIDO])
GO
ALTER TABLE [dbo].[PRODUCTOS_PEDIDO] CHECK CONSTRAINT [FK_PRODUCTOS_PEDIDO_PEDIDOS]
GO
ALTER TABLE [dbo].[PRODUCTOS_PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTOS_PEDIDO_PRODUCTOS] FOREIGN KEY([IDPRODUCTO])
REFERENCES [dbo].[PRODUCTOS] ([IDPRODUCTO])
GO
ALTER TABLE [dbo].[PRODUCTOS_PEDIDO] CHECK CONSTRAINT [FK_PRODUCTOS_PEDIDO_PRODUCTOS]
GO
ALTER TABLE [dbo].[RESTAURANTES]  WITH CHECK ADD  CONSTRAINT [FK_RESTAURANTES_CATEGORIAS_RESTAURANTES] FOREIGN KEY([IDCATEGORIA])
REFERENCES [dbo].[CATEGORIAS_RESTAURANTES] ([IDCATEGORIA])
GO
ALTER TABLE [dbo].[RESTAURANTES] CHECK CONSTRAINT [FK_RESTAURANTES_CATEGORIAS_RESTAURANTES]
GO
ALTER TABLE [dbo].[USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USUARIOS_TIPOS_USUARIOS] FOREIGN KEY([TIPOUSUARIO])
REFERENCES [dbo].[TIPOS_USUARIOS] ([IDTIPO])
GO
ALTER TABLE [dbo].[USUARIOS] CHECK CONSTRAINT [FK_USUARIOS_TIPOS_USUARIOS]
GO
ALTER TABLE [dbo].[VALORACIONES_RESTAURANTE]  WITH CHECK ADD  CONSTRAINT [FK_VALORACIONES_RESTAURANTE_RESTAURANTES] FOREIGN KEY([IDRESTAURANTE])
REFERENCES [dbo].[RESTAURANTES] ([IDRESTAURANTE])
GO
ALTER TABLE [dbo].[VALORACIONES_RESTAURANTE] CHECK CONSTRAINT [FK_VALORACIONES_RESTAURANTE_RESTAURANTES]
GO
/****** Object:  StoredProcedure [dbo].[SP_PRODUCTOS_CATEGORIA]    Script Date: 18/03/2024 10:02:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[SP_PRODUCTOS_CATEGORIA]
(@RESTAURANTE INT, @CATEGORIA INT)
AS
	SELECT P.IDPRODUCTO, P.NOMBRE, P.DESCRIPCION,
	P.PRECIO, P.IMAGEN, P.IDRESTAURANTE
	FROM PRODUCTOS P
	INNER JOIN PRODUCTO_CATEGORIAS PC
	ON P.IDPRODUCTO = PC.IDPRODUCTO
	WHERE PC.IDCATEGORIA = @CATEGORIA
	AND P.IDRESTAURANTE = @RESTAURANTE
GO
USE [master]
GO
ALTER DATABASE [BBDDPROYECTO] SET  READ_WRITE 
GO
